apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.trainee701-srecon19.innovlabs.io"
  acme:
    config:
    - dns01:
        provider: cloud-dns
      domains:
      - "*.trainee701-srecon19.innovlabs.io"
      - "trainee701-srecon19.innovlabs.io"
